version: '3.8'

services:
  django:
    image: stigito/django-weather:1.1
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weather