# Generated by Django 5.0.3 on 2024-03-19 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_rename_noontemp_daytemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytemp',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daytemp',
            name='temp',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
